### ISSUE TITLE
TestAuthWithoutSigner failure in CI

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#288]
```
--- FAIL: TestAuthWithoutSigner (0.12s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9c0202]

goroutine 99 [running]:
testing.tRunner.func1(0xc0003eb800)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0xfd0940, 0x1d7a550)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
go.mozilla.org/autograph/signer/contentsignaturepki.GetX5U(0xc000040070, 0x69, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/go.mozilla.org/autograph/signer/contentsignaturepki/upload.go:100 +0x212
go.mozilla.org/autograph/signer/contentsignaturepki.(*ContentSigner).makeAndUploadChain(0xc000202c40, 0x1046520, 0xc000250cc0)
	/go/src/go.mozilla.org/autograph/signer/contentsignaturepki/x509.go:57 +0xd1
go.mozilla.org/autograph/signer/contentsignaturepki.New(0xc0004c0398, 0x8, 0xc0004a7a20, 0x13, 0x0, 0x0, 0xc00061a360, 0x120, 0xc0004ca000, 0x36f, ...)
	/go/src/go.mozilla.org/autograph/signer/contentsignaturepki/contentsignature.go:128 +0x7d5
go.mozilla.org/autograph.(*autographer).addSigners(0xc00010e140, 0xc000231000, 0xf, 0xf, 0x502470, 0x1)
	/go/src/go.mozilla.org/autograph/main.go:334 +0xf35
go.mozilla.org/autograph.TestAuthWithoutSigner(0xc0003eb800)
	/go/src/go.mozilla.org/autograph/handlers_test.go:426 +0xa3
testing.tRunner(0xc0003eb800, 0x11a85f8)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
```

https://circleci.com/gh/mozilla-services/autograph/2762

**Comment by g-k** [comment]
Possibly related we have:

```
--- FAIL: TestAddDuplicateAuthorization (0.13s)
    authorize_test.go:192: expected authorization loading to fail with duplicate error but got: runtime error: invalid memory address or nil pointer dereference
```

https://circleci.com/gh/mozilla-services/autograph/2978

**Comment by g-k** [comment]
https://circleci.com/gh/mozilla-services/autograph/3039

**Comment by jvehent** [comment]
It shouldn't go all the way to `contentsignaturepki`. investigating.

**Comment by g-k** [comment]
https://circleci.com/gh/mozilla-services/autograph/3271

**Comment by g-k** [comment]
refs: #392

**Comment by jvehent** [comment]
I haven't been able to reproduce this locally and haven't seen it in a while in CI. Have we accidentally fixed this?

**Comment by g-k** [comment]
Yeah I haven't seen this in awhile, can reopen if it pops up again.

Maybe the auth refactor or hawk TS skew fix addressed it.
