### ISSUE TITLE
intermittent test failures on heartbeat test in CI

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph#82]
segfault on test like TestMain / waiting for socket / socket cannot be used

saw this on a docs-only change (but [this rebuild](https://travis-ci.org/mozilla-services/autograph/builds/370081502?utm_source=github_status&utm_medium=notification) cleared the logs) and :ulfr has mentioned seeing something like this too.

Will add an example if I see it again.

**Comment by g-k** [comment]
```log
{"Timestamp":1524493401458994302,"Time":"2018-04-23T14:23:21Z","Type":"app.log","Logger":"autograph","Hostname":"travis-job-a16b401d-6f1f-441e-9430-7bc0a3c50b12","EnvVersion":"2.0","Pid":6802,"Severity":6,"Fields":{"msg":"starting autograph on 0.0.0.0:8000"}}
--- FAIL: TestStartMain (0.26s)
	main_test.go:282: Get http://localhost:8000/__heartbeat__: dial tcp 127.0.0.1:8000: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9fe752]
goroutine 54 [running]:
testing.tRunner.func1(0xc4205e41e0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:742 +0x29d
panic(0xac1ee0, 0xfbbdd0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
go.mozilla.org/autograph.TestStartMain(0xc4205e41e0)
	/home/travis/gopath/src/go.mozilla.org/autograph/main_test.go:284 +0xd2
testing.tRunner(0xc4205e41e0, 0xbc61c0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:824 +0x2e0
FAIL	go.mozilla.org/autograph	6.914s
make: *** [testautograph] Error 1
```

https://travis-ci.org/mozilla-services/autograph/builds/370119935?utm_source=github_status&utm_medium=notification

**Comment by g-k** [comment]
Looks like we just need to wait for the server to start listening on the port.

**Comment by jvehent** [comment]
Maybe gate it with `until curl localhost:8000/__version__ &>/dev/null; do :; done` ?

**Comment by g-k** [comment]
https://travis-ci.org/mozilla-services/autograph/builds/438595582

**Comment by g-k** [comment]
Haven't seen this lately. Closing, will reopen if it reoccurs and gets annoying.
